# Generated by Django 5.2.2 on 2025-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmentType',
            field=models.CharField(default='General Checkup', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timePreference',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
