# Generated by Django 5.2.2 on 2025-06-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0002_remove_appointment_date_appointment_appointmentdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
