# Generated by Django 5.2.2 on 2025-07-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0004_appointment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
