# Generated by Django 5.2.2 on 2025-07-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0005_appointment_status_message_alter_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
