# Generated by Django 5.2.2 on 2025-07-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0007_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sent_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
